export const ERROR_CODE = {
    ENTER_NAME: 'ENTER_NAME', ENTER_PRICE: 'ENTER_PRICE',
    PRICE_MORE_THEN_TEN: 'PRICE_MORE_THEN_TEN',
    PRICE_SHOULD_MULTIPLE_OF_TEN: 'PRICE_SHOULD_MULTIPLE_OF_TEN', ENTER_QUANTITY: 'ENTER_QUANTITY',
    QUANTITY_SHOULD_MORE_THAN_ZERO: 'QUANTITY_SHOULD_MORE_THAN_ZERO',
    ENTER_BALANCE: 'ENTER_BALANCE', BALANCE_SHOULD_MORE_THAN_ZERO: 'BALANCE_SHOULD_MORE_THAN_ZERO',
    BALANCE_SHOULD_MULTIPLE_OF_TEN: 'BALANCE_SHOULD_MULTIPLE_OF_TEN',
    NOT_ENOUGH_BALANCE: 'NOT_ENOUGH_BALANCE',
}
export const ALERT_COMMENTS = {
    ENTER_NAME: '상품명을 입력해주세요', ENTER_PRICE: '가격을 입력해주세요', PRICE_MORE_THEN_TEN: '가격은 10원 보다 비싸야합니다',
    PRICE_SHOULD_MULTIPLE_OF_TEN: '가격은 10원 단위만 가능합니다', ENTER_QUANTITY: '수량을 입력해주세요',
    QUANTITY_SHOULD_MORE_THAN_ZERO: '수량은 0보다 커야합니다', ENTER_BALANCE: '금액을 입력해주세요',
    BALANCE_SHOULD_MORE_THAN_ZERO: '금액은 0보다 커야합니다',
    BALANCE_SHOULD_MULTIPLE_OF_TEN: '금액은 10원 단위만 가능합니다', NOT_ENOUGH_BALANCE: '소지금이 부족합니다!'
}